# coding: utf-8

# flake8: noqa

"""
    Data Cleaner

    An API to clean a persons data  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from integrationTests.swaggerClient.api.default_api import DefaultApi

# import ApiClient
from integrationTests.swaggerClient.api_client import ApiClient
from integrationTests.swaggerClient.configuration import Configuration
# import models into sdk package
