# coding: utf-8

# flake8: noqa

"""
    Preference Provider

    An API to get details about a persons preferences  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from queryPreferenceProvider.swaggerClient.api.default_api import DefaultApi

# import ApiClient
from queryPreferenceProvider.swaggerClient.api_client import ApiClient
from queryPreferenceProvider.swaggerClient.configuration import Configuration
# import models into sdk package
